export interface Sound {
  id: string;
  name: string;
  emoji: string;
  description: string;
  isPremium: boolean;
  color: string;
  asset: any;
}

export const SOUNDS: Sound[] = [
  // FREE (5)
  {
    id: 'white_noise',
    name: 'White Noise',
    emoji: '〰️',
    description: 'Classic static noise for deep sleep',
    isPremium: false,
    color: '#6C63FF',
    asset: require('../assets/sounds/white_noise.wav'),
  },
  {
    id: 'pink_noise',
    name: 'Pink Noise',
    emoji: '🌸',
    description: 'Softer than white noise, easier on the ears',
    isPremium: false,
    color: '#E91E8C',
    asset: require('../assets/sounds/pink_noise.wav'),
  },
  {
    id: 'rain',
    name: 'Rain',
    emoji: '🌧️',
    description: 'Gentle rainfall to calm your mind',
    isPremium: false,
    color: '#4A9EBF',
    asset: require('../assets/sounds/rain.wav'),
  },
  {
    id: 'ocean',
    name: 'Ocean Waves',
    emoji: '🌊',
    description: 'Relaxing ocean waves on the shore',
    isPremium: false,
    color: '#0077B6',
    asset: require('../assets/sounds/ocean.wav'),
  },
  {
    id: 'fan',
    name: 'Fan',
    emoji: '💨',
    description: 'Steady fan hum for focus and sleep',
    isPremium: false,
    color: '#5C7A9E',
    asset: require('../assets/sounds/fan.wav'),
  },

  // PRO (25)
  {
    id: 'brown_noise',
    name: 'Brown Noise',
    emoji: '🟤',
    description: 'Deeper, warmer noise for relaxation',
    isPremium: true,
    color: '#8B5E3C',
    asset: require('../assets/sounds/brown_noise.wav'),
  },
  {
    id: 'gray_noise',
    name: 'Gray Noise',
    emoji: '🌫️',
    description: 'Psychoacoustically balanced noise',
    isPremium: true,
    color: '#7B8794',
    asset: require('../assets/sounds/gray_noise.wav'),
  },
  {
    id: 'thunderstorm',
    name: 'Thunderstorm',
    emoji: '⛈️',
    description: 'Distant thunder and heavy rain',
    isPremium: true,
    color: '#4A4E69',
    asset: require('../assets/sounds/thunderstorm.wav'),
  },
  {
    id: 'heavy_rain',
    name: 'Heavy Rain',
    emoji: '🌩️',
    description: 'Intense downpour for deep focus',
    isPremium: true,
    color: '#1E6091',
    asset: require('../assets/sounds/heavy_rain.wav'),
  },
  {
    id: 'light_drizzle',
    name: 'Light Drizzle',
    emoji: '🌦️',
    description: 'Soft pitter-patter on a quiet evening',
    isPremium: true,
    color: '#74B9D6',
    asset: require('../assets/sounds/light_drizzle.wav'),
  },
  {
    id: 'rain_on_window',
    name: 'Rain on Window',
    emoji: '🪟',
    description: 'Raindrops tapping gently on glass',
    isPremium: true,
    color: '#3A7CA5',
    asset: require('../assets/sounds/rain_on_window.wav'),
  },
  {
    id: 'waterfall',
    name: 'Waterfall',
    emoji: '💦',
    description: 'Powerful cascading water',
    isPremium: true,
    color: '#00B4D8',
    asset: require('../assets/sounds/waterfall.wav'),
  },
  {
    id: 'stream',
    name: 'Stream',
    emoji: '🏞️',
    description: 'Peaceful babbling brook through the woods',
    isPremium: true,
    color: '#52B788',
    asset: require('../assets/sounds/stream.wav'),
  },
  {
    id: 'forest',
    name: 'Forest',
    emoji: '🌲',
    description: 'Birds and wind through the trees',
    isPremium: true,
    color: '#2D6A4F',
    asset: require('../assets/sounds/forest.wav'),
  },
  {
    id: 'morning_birds',
    name: 'Morning Birds',
    emoji: '🐦',
    description: 'Cheerful birdsong at sunrise',
    isPremium: true,
    color: '#F4A261',
    asset: require('../assets/sounds/morning_birds.wav'),
  },
  {
    id: 'night_crickets',
    name: 'Night Crickets',
    emoji: '🦗',
    description: 'Soothing cricket chorus on a warm night',
    isPremium: true,
    color: '#264653',
    asset: require('../assets/sounds/night_crickets.wav'),
  },
  {
    id: 'jungle_night',
    name: 'Jungle Night',
    emoji: '🌴',
    description: 'Exotic creatures of the tropical night',
    isPremium: true,
    color: '#1B4332',
    asset: require('../assets/sounds/jungle_night.wav'),
  },
  {
    id: 'gentle_breeze',
    name: 'Gentle Breeze',
    emoji: '🍃',
    description: 'Soft wind rustling through leaves',
    isPremium: true,
    color: '#80B918',
    asset: require('../assets/sounds/gentle_breeze.wav'),
  },
  {
    id: 'mountain_wind',
    name: 'Mountain Wind',
    emoji: '🏔️',
    description: 'Howling gusts across open peaks',
    isPremium: true,
    color: '#6B705C',
    asset: require('../assets/sounds/mountain_wind.wav'),
  },
  {
    id: 'blizzard',
    name: 'Blizzard',
    emoji: '❄️',
    description: 'Wild snowstorm for cozy indoor nights',
    isPremium: true,
    color: '#ADE8F4',
    asset: require('../assets/sounds/blizzard.wav'),
  },
  {
    id: 'fireplace',
    name: 'Fireplace',
    emoji: '🔥',
    description: 'Crackling fire for cozy nights',
    isPremium: true,
    color: '#C1440E',
    asset: require('../assets/sounds/fireplace.wav'),
  },
  {
    id: 'campfire',
    name: 'Campfire',
    emoji: '🏕️',
    description: 'Open-air fire under the stars',
    isPremium: true,
    color: '#E76F51',
    asset: require('../assets/sounds/campfire.wav'),
  },
  {
    id: 'cave_drips',
    name: 'Cave Drips',
    emoji: '🕳️',
    description: 'Water drops echoing in a quiet cave',
    isPremium: true,
    color: '#4A3728',
    asset: require('../assets/sounds/cave_drips.wav'),
  },
  {
    id: 'underwater',
    name: 'Underwater',
    emoji: '🐠',
    description: 'Deep ocean ambience with gentle bubbles',
    isPremium: true,
    color: '#023E8A',
    asset: require('../assets/sounds/underwater.wav'),
  },
  {
    id: 'singing_bowl',
    name: 'Singing Bowl',
    emoji: '🎵',
    description: 'Tibetan bowl resonance for meditation',
    isPremium: true,
    color: '#9B72CF',
    asset: require('../assets/sounds/singing_bowl.wav'),
  },
  {
    id: 'heartbeat',
    name: 'Heartbeat',
    emoji: '❤️',
    description: 'Slow calming heartbeat rhythm',
    isPremium: true,
    color: '#E63946',
    asset: require('../assets/sounds/heartbeat.wav'),
  },
  {
    id: 'airplane_cabin',
    name: 'Airplane Cabin',
    emoji: '✈️',
    description: 'Engine hum for sleeping on the go',
    isPremium: true,
    color: '#457B9D',
    asset: require('../assets/sounds/airplane_cabin.wav'),
  },
  {
    id: 'train',
    name: 'Train',
    emoji: '🚂',
    description: 'Rhythmic clatter on the railway',
    isPremium: true,
    color: '#6D4C41',
    asset: require('../assets/sounds/train.wav'),
  },
  {
    id: 'washing_machine',
    name: 'Washing Machine',
    emoji: '🌀',
    description: 'Steady drum rotation with water',
    isPremium: true,
    color: '#0288D1',
    asset: require('../assets/sounds/washing_machine.wav'),
  },
  {
    id: 'air_conditioner',
    name: 'Air Conditioner',
    emoji: '🌬️',
    description: 'Cool steady hum for hot nights',
    isPremium: true,
    color: '#48CAE4',
    asset: require('../assets/sounds/air_conditioner.wav'),
  },
];

export const FREE_SOUND_COUNT = SOUNDS.filter(s => !s.isPremium).length;
